import type { Doc } from "./_generated/dataModel";

export const isoFromMs = (ms: number) => new Date(ms).toISOString();

export const mapCategory = (c: Doc<"categories">) => ({
  id: c._id,
  name: c.name,
  icon: c.icon,
  sort_order: c.sortOrder,
  active: c.active,
  created_at: isoFromMs(c._creationTime),
  updated_at: isoFromMs(c._creationTime),
});

export const mapProduct = (p: Doc<"products">) => ({
  id: p._id,
  name: p.name,
  description: p.description,
  category: p.categoryId as string,
  base_price: p.basePrice,
  discount_price: p.discountPrice ?? null,
  discount_start_date: p.discountStartDate ? isoFromMs(p.discountStartDate) : null,
  discount_end_date: p.discountEndDate ? isoFromMs(p.discountEndDate) : null,
  discount_active: p.discountActive ?? false,
  purity_percentage: p.purityPercentage ?? 99.0,
  molecular_weight: p.molecularWeight ?? null,
  cas_number: p.casNumber ?? null,
  sequence: p.sequence ?? null,
  storage_conditions: p.storageConditions ?? "Store at -20°C",
  inclusions: p.inclusions ?? null,
  stock_quantity: p.stockQuantity,
  available: p.available,
  featured: p.featured,
  image_url: p.imageUrl ?? null,
  safety_sheet_url: p.safetySheetUrl ?? null,
  created_at: isoFromMs(p._creationTime),
  updated_at: isoFromMs(p._creationTime),
});

export const mapVariation = (v: Doc<"productVariations">) => ({
  id: v._id,
  product_id: v.productId as string,
  name: v.name,
  quantity_mg: v.quantityMg,
  price: v.price,
  discount_price: v.discountPrice ?? null,
  discount_active: v.discountActive ?? false,
  disposable_pen_price: null,
  reusable_pen_price: null,
  stock_quantity: v.stockQuantity,
  created_at: isoFromMs(v._creationTime),
});

export const mapPaymentMethod = (m: Doc<"paymentMethods">) => ({
  id: m._id,
  name: m.name,
  account_number: m.accountNumber ?? "",
  account_name: m.accountName ?? "",
  qr_code_url: m.qrCodeUrl ?? "",
  active: m.active,
  sort_order: m.sortOrder,
  created_at: isoFromMs(m._creationTime),
  updated_at: isoFromMs(m._creationTime),
});

export const mapShippingLocation = (s: Doc<"shippingLocations">) => ({
  id: s.code,
  _docId: s._id,
  name: s.name,
  fee: s.fee,
  is_active: s.isActive,
  order_index: s.orderIndex,
});

export const mapCourier = (c: Doc<"couriers">) => ({
  id: c._id,
  code: c.code,
  name: c.name,
  tracking_url_template: c.trackingUrlTemplate ?? null,
  is_active: c.isActive,
  sort_order: c.sortOrder ?? 0,
  created_at: isoFromMs(c._creationTime),
});

export const mapPromoCode = (p: Doc<"promoCodes">) => ({
  id: p._id,
  code: p.code,
  discount_type: p.discountType,
  discount_value: p.discountValue,
  min_purchase_amount: p.minPurchaseAmount ?? 0,
  max_discount_amount: p.maxDiscountAmount ?? null,
  start_date: p.startDate ? isoFromMs(p.startDate) : null,
  end_date: p.endDate ? isoFromMs(p.endDate) : null,
  usage_limit: p.usageLimit ?? null,
  usage_count: p.usageCount,
  active: p.active,
  created_at: isoFromMs(p._creationTime),
  updated_at: isoFromMs(p._creationTime),
});

export const mapOrder = (o: Doc<"orders">) => ({
  id: o._id,
  order_number: o.orderNumber ?? null,
  customer_name: o.customerName,
  customer_email: o.customerEmail,
  customer_phone: o.customerPhone,
  contact_method: o.contactMethod ?? null,
  shipping_address: o.shippingAddress,
  shipping_city: o.shippingCity ?? null,
  shipping_state: o.shippingState ?? null,
  shipping_zip_code: o.shippingZipCode ?? null,
  shipping_country: o.shippingCountry ?? null,
  shipping_barangay: o.shippingBarangay ?? null,
  shipping_region: o.shippingRegion ?? null,
  shipping_location: o.shippingLocation ?? null,
  courier_id: (o.courierId as string | undefined) ?? null,
  shipping_fee: o.shippingFee ?? 0,
  order_items: o.orderItems,
  subtotal: o.subtotal ?? null,
  total_price: o.totalPrice,
  pricing_mode: o.pricingMode ?? "PHP",
  payment_method_id: o.paymentMethodId ?? null,
  payment_method_name: o.paymentMethodName ?? null,
  payment_status: o.paymentStatus ?? "pending",
  payment_proof_url: o.paymentProofUrl ?? null,
  promo_code_id: (o.promoCodeId as string | undefined) ?? null,
  promo_code: o.promoCode ?? null,
  discount_applied: o.discountApplied ?? 0,
  order_status: o.orderStatus ?? "new",
  notes: o.notes ?? null,
  admin_notes: o.adminNotes ?? null,
  tracking_number: o.trackingNumber ?? null,
  tracking_courier: o.trackingCourier ?? null,
  shipping_provider: o.shippingProvider ?? null,
  shipping_note: o.shippingNote ?? null,
  shipped_at: o.shippedAt ? isoFromMs(o.shippedAt) : null,
  created_at: isoFromMs(o._creationTime),
  updated_at: o.updatedAt ? isoFromMs(o.updatedAt) : isoFromMs(o._creationTime),
});

export const mapCoa = (c: Doc<"coaReports">) => ({
  id: c._id,
  product_name: c.productName,
  batch: c.batch ?? "",
  test_date: c.testDate,
  purity_percentage: c.purityPercentage,
  quantity: c.quantity,
  task_number: c.taskNumber,
  verification_key: c.verificationKey,
  image_url: c.imageUrl,
  featured: c.featured,
  manufacturer: c.manufacturer ?? "",
  laboratory: c.laboratory ?? "",
  created_at: isoFromMs(c._creationTime),
  updated_at: isoFromMs(c._creationTime),
});

export const mapFaq = (f: Doc<"faqs">) => ({
  id: f._id,
  question: f.question,
  answer: f.answer,
  category: f.category,
  order_index: f.orderIndex,
  is_active: f.isActive,
  created_at: isoFromMs(f._creationTime),
  updated_at: isoFromMs(f._creationTime),
});

export const mapProtocol = (p: Doc<"protocols">) => ({
  id: p._id,
  name: p.name,
  category: p.category,
  dosage: p.dosage,
  frequency: p.frequency,
  duration: p.duration,
  notes: p.notes,
  storage: p.storage,
  sort_order: p.sortOrder,
  active: p.active,
  product_id: (p.productId as string | undefined) ?? undefined,
  image_url: p.imageUrl ?? null,
  content_type: p.contentType ?? "text",
  file_url: p.fileUrl ?? null,
  created_at: isoFromMs(p._creationTime),
  updated_at: isoFromMs(p._creationTime),
});

export const mapArticle = (a: Doc<"articles">) => ({
  id: a._id,
  title: a.title,
  preview: a.preview ?? null,
  content: a.content,
  cover_image: a.coverImage ?? null,
  author: a.author,
  published_date: a.publishedDate,
  display_order: a.displayOrder,
  is_enabled: a.isEnabled,
  created_at: isoFromMs(a._creationTime),
  updated_at: isoFromMs(a._creationTime),
});
